export const types: any = {
  lucky7: "lucky7",
  lucky7B: "lucky7B",
  queen: "Queen",
  aaa: "AAA",
  ddb: "ddb",
  baccarat: "baccarat",
  baccarat2: "baccarat2",
  dt20: "dragontiger20A",
  card32: "card32a",
  Tp1Day: "Tp1Day",
  dt20b: "dt20b",
  onedaypoker: "onedaypoker",
  onedaypoker20: "onedaypoker20",
  teen20: "t20Odds",
  dragontiger1Day: "dragontiger1Day",
  dtl20: "dtl20",
  race2020: "race2020",
  poker6player: "poker6player",
  cmeter2020: "cmeter2020",
  Superover: "Superover",
  testtp: "testtp",
  Cards3J: "Cards3J",
  fivewicket: "fivewicket",
  card32b: "card32b",
  opentp: "opentp",
  cricket2020: "cricket2020",
  Andarbahar2: "Andarbahar2",
  Andarbahar: "Andarbahar",
  warcasino: "warcasino",
  worlimatka: "worlimatka",
  worliinstant: "worliinstant",
};

export const eventJson: any = {
  //@ts-ignore
  lucky7: () => import("../event-json/lucky7.json"),
  lucky7B: () => import("../event-json/lucky7B.json"),
  queen: () => import("../event-json/queen.json"),
  Queen: () => import("../event-json/queen.json"),
  aaa: () => import("../event-json/AAA.json"),
  ddb: () => import("../event-json/ddb.json"),
  baccarat: () => import("../event-json/baccarat.json"),
  baccarat2: () => import("../event-json/baccarat2.json"),
  dt20: () => import("../event-json/dt20.json"),
  card32: () => import("../event-json/card32.json"),
  Tp1Day: () => import("../event-json/Tp1Day.json"),
  dt20b: () => import("../event-json/dt20b.json"),
  onedaypoker: () => import("../event-json/onedaypoker.json"),
  onedaypoker20: () => import("../event-json/onedaypoker20.json"),
  teen20: () => import("../event-json/teen20.json"),
  dragontiger1Day: () => import("../event-json/dragontiger1Day.json"),
  dtl20: () => import("../event-json/dtl20.json"),
  race2020: () => import("../event-json/race2020.json"),
  poker6player: () => import("../event-json/poker6player.json"),
  cmeter2020: () => import("../event-json/cmeter2020.json"),
  Superover: () => import("../event-json/Superover.json"),
  testtp: () => import("../event-json/testtp.json"),
  Cards3J: () => import("../event-json/Card3J.json"),
  fivewicket: () => import("../event-json/fivewicket.json"),
  card32b: () => import("../event-json/card32b.json"),
  opentp: () => import("../event-json/opentp.json"),
  cricket2020: () => import("../event-json/cricket2020.json"),
  Andarbahar2: () => import("../event-json/Andarbahar2.json"),
  Andarbahar: () => import("../event-json/Andarbahar.json"),
  warcasino: () => import("../event-json/warcasino.json"),
  worlimatka: () => import("../event-json/worlimatka.json"),
  worliinstant: () => import("../event-json/worliinstant.json"),
};
